# This is a workflow to test and deploy our demo app.

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEMO_HOME: /home/runner/work/swe_project/swe_project/
  PYTHONPATH: /home/runner/work/swe_project/swe_project/
  URL: https://project-finder.herokuapp.com/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environment: heroku-deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Install Python packages.
        run: make dev_env

